<a href="https://colab.research.google.com/github/FernyCat/Practica2.3/blob/main/Practica2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Archivo
data = pd.read_csv('/content/drive/MyDrive/Wine.csv', header=None)
data.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

## Eliminamos la primera columna

In [ ]:
# 1- Eliminar primera columna
data = data.drop(0,axis=1)
#Agregar nombres a las columnas para facilitar su uso
columns = ['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13']
data.columns = columns

### Normalizacion

In [ ]:
# Metodo min max
new_data = data
for col in new_data.columns:
  new_data[col] = (data[col] - data[col].min()) / (data[col].max() - data[col].min())

new_data.head()

X1        X2        X3        X4        X5        X6        X7  \
0  0.842105  0.191700  0.572193  0.257732  0.619565  0.627586  0.573840   
1  0.571053  0.205534  0.417112  0.030928  0.326087  0.575862  0.510549   
2  0.560526  0.320158  0.700535  0.412371  0.336957  0.627586  0.611814   
3  0.878947  0.239130  0.609626  0.319588  0.467391  0.989655  0.664557   
4  0.581579  0.365613  0.807487  0.536082  0.521739  0.627586  0.495781   

         X8        X9       X10       X11       X12       X13  
0  0.283019  0.593060  0.372014  0.455285  0.970696  0.561341  
1  0.245283  0.274448  0.264505  0.463415  0.780220  0.550642  
2  0.320755  0.757098  0.375427  0.447154  0.695971  0.646933  
3  0.207547  0.558360  0.556314  0.308943  0.798535  0.857347  
4  0.490566  0.444795  0.259386  0.455285  0.608059  0.325963

## Matriz de distancias

In [ ]:
import math

n_points = len(new_data)
distance_matrix = np.zeros((n_points, n_points))

for i in range(n_points):
    for j in range(i + 1, n_points):
        point1 = new_data.iloc[i]
        point2 = new_data.iloc[j]

        sum = 0

        for col in new_data.columns:
            sum += (point1[col] - point2[col]) ** 2

        euclidean_distance = math.sqrt(sum)
        distance_matrix[i][j] = euclidean_distance
        distance_matrix[j][i] = euclidean_distance

distance_matrix

array([[0.        , 0.62683248, 0.57331769, ..., 1.42788461, 1.35195151,
        1.52021614],
       [0.62683248, 0.        , 0.72090904, ..., 1.33922263, 1.27502377,
        1.49688615],
       [0.57331769, 0.72090904, 0.        , ..., 1.28971502, 1.22263247,
        1.34533449],
       ...,
       [1.42788461, 1.33922263, 1.28971502, ..., 0.        , 0.39924775,
        0.60992201],
       [1.35195151, 1.27502377, 1.22263247, ..., 0.39924775, 0.        ,
        0.6145566 ],
       [1.52021614, 1.49688615, 1.34533449, ..., 0.60992201, 0.6145566 ,
        0.        ]])

In [ ]:
#distancia al cuadrado
distancia_2 = distance_matrix ** 2
distancia_2

array([[0.        , 0.39291896, 0.32869318, ..., 2.03885446, 1.8277729 ,
        2.31105713],
       [0.39291896, 0.        , 0.51970985, ..., 1.79351726, 1.62568561,
        2.24066814],
       [0.32869318, 0.51970985, 0.        , ..., 1.66336484, 1.49483016,
        1.8099249 ],
       ...,
       [2.03885446, 1.79351726, 1.66336484, ..., 0.        , 0.15939876,
        0.37200486],
       [1.8277729 , 1.62568561, 1.49483016, ..., 0.15939876, 0.        ,
        0.37767981],
       [2.31105713, 2.24066814, 1.8099249 , ..., 0.37200486, 0.37767981,
        0.        ]])

## Matriz centalizada

In [ ]:
#doble centrado
n = len(distance_matrix)
j = np.ones(n)
I = np.eye(n)
C = I - ((j)/n)
C

array([[ 0.99438202, -0.00561798, -0.00561798, ..., -0.00561798,
        -0.00561798, -0.00561798],
       [-0.00561798,  0.99438202, -0.00561798, ..., -0.00561798,
        -0.00561798, -0.00561798],
       [-0.00561798, -0.00561798,  0.99438202, ..., -0.00561798,
        -0.00561798, -0.00561798],
       ...,
       [-0.00561798, -0.00561798, -0.00561798, ...,  0.99438202,
        -0.00561798, -0.00561798],
       [-0.00561798, -0.00561798, -0.00561798, ..., -0.00561798,
         0.99438202, -0.00561798],
       [-0.00561798, -0.00561798, -0.00561798, ..., -0.00561798,
        -0.00561798,  0.99438202]])

In [ ]:
B = (-1/2)* np.dot(np.dot(C,distancia_2),C)
B

array([[ 0.68743939,  0.36564401,  0.39601011, ..., -0.27554511,
        -0.25098813, -0.36075568],
       [ 0.36564401,  0.43676759,  0.17516587, ..., -0.27821241,
        -0.27528039, -0.45089708],
       [ 0.39601011,  0.17516587,  0.43327401, ..., -0.21488299,
        -0.21159945, -0.23727225],
       ...,
       [-0.27554511, -0.27821241, -0.21488299, ...,  0.80032485,
         0.63964167,  0.66521318],
       [-0.25098813, -0.27528039, -0.21159945, ...,  0.63964167,
         0.63835725,  0.58139192],
       [-0.36075568, -0.45089708, -0.23727225, ...,  0.66521318,
         0.58139192,  0.90210639]])

In [ ]:
#Calcular Vectores propios
valores_propios , vectores_propios = np.linalg.eig(B)
print('Valores propios = ',valores_propios)
print('Vectores propios = ', vectores_propios)
K = 2
sorted_indices = np.argsort(valores_propios)[::-1]
sorted_eigenvalues = valores_propios[sorted_indices]
sorted_eigenvectors = vectores_propios[:,sorted_indices]

Valores propios =  [ 3.89563189e+01+0.00000000e+00j  1.81355686e+01+0.00000000e+00j
  8.18491754e+00+0.00000000e+00j  7.09986965e+00+0.00000000e+00j
  5.32040212e+00+0.00000000e+00j  4.45382682e+00+0.00000000e+00j
  3.50269910e+00+0.00000000e+00j  2.30279143e+00+0.00000000e+00j
  2.15191172e+00+0.00000000e+00j  2.17428771e+00+0.00000000e+00j
  1.32050922e+00+0.00000000e+00j  1.21720766e+00+0.00000000e+00j
  7.79227303e-01+0.00000000e+00j -1.84803009e-15+4.45361153e-15j
 -1.84803009e-15-4.45361153e-15j -3.72880110e-15+2.04394035e-15j
 -3.72880110e-15-2.04394035e-15j  4.30227252e-15+0.00000000e+00j
 -3.71842613e-15+7.55591533e-16j -3.71842613e-15-7.55591533e-16j
  3.32129643e-15+1.29415377e-15j  3.32129643e-15-1.29415377e-15j
  3.61250413e-15+8.33974134e-17j  3.61250413e-15-8.33974134e-17j
 -3.15537498e-15+0.00000000e+00j  2.10453808e-15+2.15262287e-15j
  2.10453808e-15-2.15262287e-15j  3.04529284e-15+6.27426669e-16j
  3.04529284e-15-6.27426669e-16j  2.12318888e-15+1.69024926e-15j
  2.12

In [ ]:
n_components = 10
X_reduced = vectores_propios[:, :n_components] * np.sqrt(valores_propios[:n_components])
X_reduced

array([[-0.70633576+0.j,  0.25319275+0.j,  0.02409269+0.j, ...,
         0.13851902+0.j,  0.27744324+0.j, -0.11862666+0.j],
       [-0.4849768 +0.j,  0.00882289+0.j, -0.28048205+0.j, ...,
        -0.18119338+0.j,  0.11494849+0.j, -0.02806622+0.j],
       [-0.52117227+0.j,  0.18918722+0.j,  0.19621674+0.j, ...,
         0.02317846+0.j, -0.01727012+0.j,  0.2221326 +0.j],
       ...,
       [ 0.62631289+0.j,  0.54685701+0.j, -0.03049476+0.j, ...,
        -0.03713893+0.j,  0.07354422+0.j,  0.00146496+0.j],
       [ 0.5729911 +0.j,  0.42551609+0.j, -0.09453672+0.j, ...,
        -0.02466179+0.j,  0.19659748+0.j, -0.01139898+0.j],
       [ 0.701764  +0.j,  0.51350498+0.j,  0.29390996+0.j, ...,
         0.11174192+0.j, -0.0509633 +0.j, -0.10294569+0.j]])

In [ ]:
X_reduced= pd.DataFrame(X_reduced)
columns = ['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10']
X_reduced.columns = columns
print(X_reduced.head())

                   X1                  X2                  X3  \
0 -0.706336+0.000000j  0.253193+0.000000j  0.024093+0.000000j   
1 -0.484977+0.000000j  0.008823+0.000000j -0.280482+0.000000j   
2 -0.521172+0.000000j  0.189187+0.000000j  0.196217+0.000000j   
3 -0.821644+0.000000j  0.580906+0.000000j  0.081110+0.000000j   
4 -0.202546+0.000000j  0.059467+0.000000j  0.300240+0.000000j   

                   X4                  X5                  X6  \
0 -0.013263+0.000000j  0.026580+0.000000j -0.074364+0.000000j   
1 -0.075898+0.000000j  0.238634+0.000000j -0.071877+0.000000j   
2  0.015784+0.000000j -0.045045+0.000000j  0.087116+0.000000j   
3 -0.012235+0.000000j  0.004805+0.000000j  0.081987+0.000000j   
4  0.102051+0.000000j -0.105777+0.000000j -0.116790+0.000000j   

                   X7                  X8                  X9  \
0 -0.065172+0.000000j  0.138519+0.000000j  0.277443+0.000000j   
1 -0.000686+0.000000j -0.181193+0.000000j  0.114948+0.000000j   
2 -0.125605+0.000000j  