<a href="https://colab.research.google.com/github/FernyCat/Practica2.3/blob/main/Practica2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import numpy as np
import pandas as pd

In [6]:
#Archivo
data = pd.read_csv('/content/drive/MyDrive/Wine.csv', header=None)
data.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

## Eliminamos la primera columna

In [8]:
# 1- Eliminar primera columna
data = data.drop(0,axis=1)
#Agregar nombres a las columnas para facilitar su uso
columns = ['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13']
data.columns = columns

### Normalizacion

In [9]:
# Metodo min max
new_data = data
for col in new_data.columns:
  new_data[col] = (data[col] - data[col].min()) / (data[col].max() - data[col].min())

new_data.head()

X1        X2        X3        X4        X5        X6        X7  \
0  0.842105  0.191700  0.572193  0.257732  0.619565  0.627586  0.573840   
1  0.571053  0.205534  0.417112  0.030928  0.326087  0.575862  0.510549   
2  0.560526  0.320158  0.700535  0.412371  0.336957  0.627586  0.611814   
3  0.878947  0.239130  0.609626  0.319588  0.467391  0.989655  0.664557   
4  0.581579  0.365613  0.807487  0.536082  0.521739  0.627586  0.495781   

         X8        X9       X10       X11       X12       X13  
0  0.283019  0.593060  0.372014  0.455285  0.970696  0.561341  
1  0.245283  0.274448  0.264505  0.463415  0.780220  0.550642  
2  0.320755  0.757098  0.375427  0.447154  0.695971  0.646933  
3  0.207547  0.558360  0.556314  0.308943  0.798535  0.857347  
4  0.490566  0.444795  0.259386  0.455285  0.608059  0.325963

## Matriz de distancias

In [10]:
import math

n_points = len(new_data)
distance_matrix = np.zeros((n_points, n_points))

for i in range(n_points):
    for j in range(i + 1, n_points):
        point1 = new_data.iloc[i]
        point2 = new_data.iloc[j]

        sum = 0

        for col in new_data.columns:
            sum += (point1[col] - point2[col]) ** 2

        euclidean_distance = math.sqrt(sum)
        distance_matrix[i][j] = euclidean_distance
        distance_matrix[j][i] = euclidean_distance

distance_matrix

array([[0.        , 0.62683248, 0.57331769, ..., 1.42788461, 1.35195151,
        1.52021614],
       [0.62683248, 0.        , 0.72090904, ..., 1.33922263, 1.27502377,
        1.49688615],
       [0.57331769, 0.72090904, 0.        , ..., 1.28971502, 1.22263247,
        1.34533449],
       ...,
       [1.42788461, 1.33922263, 1.28971502, ..., 0.        , 0.39924775,
        0.60992201],
       [1.35195151, 1.27502377, 1.22263247, ..., 0.39924775, 0.        ,
        0.6145566 ],
       [1.52021614, 1.49688615, 1.34533449, ..., 0.60992201, 0.6145566 ,
        0.        ]])

In [11]:
#distancia al cuadrado
distancia_2 = distance_matrix ** 2
distancia_2

array([[0.        , 0.39291896, 0.32869318, ..., 2.03885446, 1.8277729 ,
        2.31105713],
       [0.39291896, 0.        , 0.51970985, ..., 1.79351726, 1.62568561,
        2.24066814],
       [0.32869318, 0.51970985, 0.        , ..., 1.66336484, 1.49483016,
        1.8099249 ],
       ...,
       [2.03885446, 1.79351726, 1.66336484, ..., 0.        , 0.15939876,
        0.37200486],
       [1.8277729 , 1.62568561, 1.49483016, ..., 0.15939876, 0.        ,
        0.37767981],
       [2.31105713, 2.24066814, 1.8099249 , ..., 0.37200486, 0.37767981,
        0.        ]])

## Matriz centalizada

In [12]:
#doble centrado
n = len(distance_matrix)
j = np.ones(n)
I = np.eye(n)
C = I - ((j)/n)
C

array([[ 0.99438202, -0.00561798, -0.00561798, ..., -0.00561798,
        -0.00561798, -0.00561798],
       [-0.00561798,  0.99438202, -0.00561798, ..., -0.00561798,
        -0.00561798, -0.00561798],
       [-0.00561798, -0.00561798,  0.99438202, ..., -0.00561798,
        -0.00561798, -0.00561798],
       ...,
       [-0.00561798, -0.00561798, -0.00561798, ...,  0.99438202,
        -0.00561798, -0.00561798],
       [-0.00561798, -0.00561798, -0.00561798, ..., -0.00561798,
         0.99438202, -0.00561798],
       [-0.00561798, -0.00561798, -0.00561798, ..., -0.00561798,
        -0.00561798,  0.99438202]])

In [13]:
B = (-1/2)* np.dot(np.dot(C,distancia_2),C)
B

array([[ 0.68743939,  0.36564401,  0.39601011, ..., -0.27554511,
        -0.25098813, -0.36075568],
       [ 0.36564401,  0.43676759,  0.17516587, ..., -0.27821241,
        -0.27528039, -0.45089708],
       [ 0.39601011,  0.17516587,  0.43327401, ..., -0.21488299,
        -0.21159945, -0.23727225],
       ...,
       [-0.27554511, -0.27821241, -0.21488299, ...,  0.80032485,
         0.63964167,  0.66521318],
       [-0.25098813, -0.27528039, -0.21159945, ...,  0.63964167,
         0.63835725,  0.58139192],
       [-0.36075568, -0.45089708, -0.23727225, ...,  0.66521318,
         0.58139192,  0.90210639]])